# Generated by Django 3.1.7 on 2021-03-27 07:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='task_name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='task',
            name='date_due',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 7, 40, 56, 770060), verbose_name='Date Due'),
        ),
    ]
