# Generated by Django 3.1.7 on 2021-03-27 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210327_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_due',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 23, 50, 5, 681639), verbose_name='Date Due'),
        ),
    ]
