# Generated by Django 3.1.7 on 2021-03-28 00:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210328_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_due',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 0, 35, 32, 996675), verbose_name='Date Due'),
        ),
    ]
